import React, { useEffect, useMemo, useState } from 'react';
import { Session } from '@supabase/supabase-js';
import { deleteRecord, getAdminSession, getProfileForAdmin, getRecords, isCurrentUserAdmin, onAdminAuthChange, saveProfile, saveRecord, signInWithGoogle, signOut } from '../services/adminService';
import { AdminContentKey, AdminEducationWork, AdminNews, AdminProfile, AdminProject, AdminQualification, AdminRecord, AdminResearch } from '../types/admin';
import { EducationWorkForm } from './admin/EducationWorkForm';
import { AdminsPage } from './admin/AdminsPage';
import { NewsForm } from './admin/NewsForm';
import { ProfileForm } from './admin/ProfileForm';
import { ProjectForm } from './admin/ProjectForm';
import { QualificationForm } from './admin/QualificationForm';
import { ResearchForm } from './admin/ResearchForm';

type Meta = { key: AdminContentKey; label: string; description: string; accent: 'indigo' | 'rose' };
const metas: Meta[] = [
  { key: 'news', label: 'News', description: 'ニュース・お知らせ', accent: 'rose' },
  { key: 'education-work', label: 'Education / Work', description: '学歴・職歴・インターン', accent: 'indigo' },
  { key: 'research', label: 'Research', description: '研究実績・画像・タグ', accent: 'rose' },
  { key: 'projects', label: 'Projects', description: '開発プロジェクト・技術タグ', accent: 'indigo' },
  { key: 'qualifications', label: 'Qualifications', description: '資格・褒賞・奨学金', accent: 'rose' },
];
const navigate = (to: string) => { window.history.pushState({}, '', to); window.dispatchEvent(new PopStateEvent('popstate')); };
const Button = ({ children, className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button {...props} className={`inline-flex h-11 items-center justify-center gap-2 border px-4 text-sm font-semibold transition-colors disabled:opacity-50 ${className}`}>{children}</button>;
const titleOf = (row: AdminRecord) => 'name' in row ? row.name : row.title;
const subOf = (row: AdminRecord) => 'label' in row ? row.label : 'subtitle' in row ? row.subtitle : row.description;
const tagsOf = (row: AdminRecord) => 'tags' in row ? row.tags : 'tech' in row ? row.tech : 'category' in row ? [row.category] : [];

const Header = ({ session }: { session: Session }) => <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-[86px] max-w-[1500px] items-center justify-between px-5 sm:px-8"><button type="button" onClick={() => navigate('/admin')} className="text-2xl font-extrabold tracking-tight">管理者画面</button><div className="flex gap-2 sm:gap-4"><span className="hidden max-w-48 truncate self-center text-sm text-slate-500 lg:block">{session.user.email}</span><Button type="button" onClick={() => window.location.assign('/')} className="hidden border-slate-200 sm:inline-flex">サイトへ</Button><Button type="button" onClick={() => navigate('/admin/admins')} className="border-slate-200">管理者一覧</Button><Button type="button" onClick={() => signOut()} className="border-slate-950 bg-slate-950 text-white">ログアウト</Button></div></div></header>;

const Login = ({ error }: { error?: string }) => { const [loading, setLoading] = useState(false); const [loginError, setLoginError] = useState(''); const login = async () => { setLoading(true); setLoginError(''); const { error: failure } = await signInWithGoogle(); if (failure) { setLoginError(failure.message); setLoading(false); } }; return <main className="grid min-h-screen place-items-center bg-[#fafbfe] px-5"><section className="w-full max-w-md border border-slate-200 bg-white p-8 shadow-sm"><p className="text-sm font-bold text-indigo-500">PORTFOLIO</p><h1 className="mt-3 text-3xl font-extrabold">Portfolio CMS</h1><p className="mt-3 text-sm leading-relaxed text-slate-500">ポートフォリオのコンテンツを管理するためにログインしてください。</p>{error && <p className="mt-5 border border-rose-200 bg-rose-50 p-3 text-sm text-rose-600">{error}</p>}{loginError && <p className="mt-5 border border-rose-200 bg-rose-50 p-3 text-sm text-rose-600">Googleログインを開始できませんでした: {loginError}</p>}<div className="mt-7 grid gap-3"><Button type="button" disabled={loading} onClick={login} className="w-full border-slate-950 bg-slate-950 text-white">{loading ? 'Googleへ移動中...' : 'Googleでログイン'}</Button><Button type="button" onClick={() => window.location.assign('/')} className="w-full border-slate-200 bg-white text-slate-700">サイトへ戻る</Button></div></section></main>; };

const Dashboard = ({ counts }: { counts: Partial<Record<AdminContentKey, number>> }) => <main className="mx-auto max-w-[1460px] px-5 py-10 sm:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><h1 className="text-4xl font-extrabold tracking-tight">Portfolio CMS</h1><p className="mt-3 text-sm text-slate-500">ポートフォリオの公開コンテンツをここから管理できます。</p></div><div className="inline-flex h-11 items-center gap-3 self-start rounded-full border border-slate-200 bg-white px-5 text-sm font-semibold"><span className="h-2.5 w-2.5 rounded-full bg-emerald-500" />Supabase is connected</div></div><div className="mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-3"><button type="button" onClick={() => navigate('/admin/profile')} className="min-h-52 border border-l-4 border-l-indigo-500 border-slate-200 bg-white p-6 text-left shadow-sm"><h2 className="text-lg font-bold">Profile</h2><p className="mt-2 text-4xl font-extrabold">1</p><p className="mt-4 text-sm text-slate-500">基本プロフィール・Hero画像</p><span className="mt-5 inline-block border border-indigo-300 px-4 py-2 text-xs font-bold text-indigo-500">EDIT</span></button>{metas.map((meta) => <button key={meta.key} type="button" onClick={() => navigate(`/admin/${meta.key}`)} className={`min-h-52 border border-l-4 border-slate-200 bg-white p-6 text-left shadow-sm ${meta.accent === 'indigo' ? 'border-l-indigo-500' : 'border-l-rose-500'}`}><h2 className="text-lg font-bold">{meta.label}</h2><p className="mt-2 text-4xl font-extrabold">{counts[meta.key] ?? '-'}</p><p className="mt-4 text-sm text-slate-500">{meta.description}</p><span className={`mt-5 inline-block border px-4 py-2 text-xs font-bold ${meta.accent === 'indigo' ? 'border-indigo-300 text-indigo-500' : 'border-rose-300 text-rose-500'}`}>MANAGE</span></button>)}</div></main>;

const ListPage = ({ meta }: { meta: Meta }) => { const [rows, setRows] = useState<AdminRecord[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [target, setTarget] = useState<AdminRecord>();
  const load = async () => { try { setRows(await getRecords(meta.key)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'データを取得できませんでした。'); } };
  useEffect(() => { load(); }, [meta.key]);
  const filtered = useMemo(() => rows.filter((row) => `${titleOf(row)} ${subOf(row)} ${tagsOf(row).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const remove = async () => { if (!target) return; try { await deleteRecord(meta.key, target.id); setRows(rows.filter((row) => row.id !== target.id)); setTarget(undefined); } catch (reason) { setError(reason instanceof Error ? reason.message : '削除できませんでした。'); } };
  return <main className="mx-auto max-w-[1460px] px-5 py-8 sm:px-8"><button type="button" onClick={() => navigate('/admin')} className="text-sm font-semibold text-slate-500">← ダッシュボードに戻る</button><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-extrabold tracking-tight">{meta.label}管理</h1><p className="mt-2 text-sm text-slate-500">{meta.description}の追加・編集・削除を行います。</p></div><Button type="button" onClick={() => navigate(`/admin/${meta.key}/new`)} className="border-indigo-600 bg-indigo-600 text-white">+ {meta.label}を追加</Button></div><section className="mt-6 border border-slate-200 bg-white p-5 shadow-sm"><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-11 w-full max-w-md border border-slate-200 px-3 text-sm outline-none focus:border-indigo-500" />{error && <p className="mt-4 text-sm text-rose-500">{error}</p>}<div className="mt-5 overflow-x-auto"><div className="min-w-[820px]"><div className="grid grid-cols-[minmax(320px,1fr)_130px_100px_160px] gap-4 border-y border-slate-200 px-3 py-3 text-xs font-bold text-slate-500"><span>{meta.label}</span><span>公開状態</span><span>表示順</span><span>操作</span></div>{filtered.map((row) => <div key={row.id} className="grid grid-cols-[minmax(320px,1fr)_130px_100px_160px] items-center gap-4 border-b border-slate-200 px-3 py-4"><div><h2 className="font-bold">{titleOf(row)}</h2><p className="mt-1 text-sm text-slate-500">{subOf(row)}</p><div className="mt-2 flex flex-wrap gap-2">{tagsOf(row).map((tag) => <span key={tag} className="border border-slate-200 bg-slate-50 px-2 py-1 text-xs text-slate-500">{tag}</span>)}</div></div><span className={`w-fit border px-3 py-1 text-xs font-bold ${row.is_published ? 'border-emerald-300 bg-emerald-50 text-emerald-600' : 'border-slate-300 text-slate-500'}`}>{row.is_published ? '公開' : '非公開'}</span><span className="text-center text-sm">{row.display_order}</span><div className="flex gap-2"><Button type="button" onClick={() => navigate(`/admin/${meta.key}/${row.id}`)} className="h-9 border-indigo-400 px-3 text-indigo-500">編集</Button><Button type="button" onClick={() => setTarget(row)} className="h-9 border-rose-400 px-3 text-rose-500">削除</Button></div></div>)}</div></div></section>{target && <div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/35 px-4"><div className="w-full max-w-sm bg-white p-6 shadow-xl"><h2 className="text-lg font-bold">このデータを削除しますか？</h2><p className="mt-2 text-sm text-slate-500">この操作は取り消せません。</p><div className="mt-5 flex justify-end gap-3"><Button type="button" onClick={() => setTarget(undefined)} className="border-slate-200">キャンセル</Button><Button type="button" onClick={remove} className="border-rose-500 bg-rose-500 text-white">削除</Button></div></div></div>}</main>; };

const EditPage = ({ meta, id }: { meta: Meta; id: string }) => { const [row, setRow] = useState<AdminRecord>(); const [defaultOrder, setDefaultOrder] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { setLoading(true); getRecords(meta.key).then((rows) => { if (id === 'new') setDefaultOrder(rows.reduce((max, item) => Math.max(max, item.display_order), -1) + 1); else setRow(rows.find((item) => item.id === id)); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)); }, [id, meta.key]); const save = async (value: Record<string, unknown>) => { try { await saveRecord(meta.key, { ...value, ...(id === 'new' ? {} : { id }) } as Partial<AdminRecord> & { id?: string }); navigate(`/admin/${meta.key}`); } catch (reason) { setError(reason instanceof Error ? reason.message : '保存できませんでした。'); } }; const form = () => { if (meta.key === 'news') return <NewsForm initial={row as AdminNews} defaultOrder={defaultOrder} onSave={save} />; if (meta.key === 'education-work') return <EducationWorkForm initial={row as AdminEducationWork} defaultOrder={defaultOrder} onSave={save} />; if (meta.key === 'research') return <ResearchForm initial={row as AdminResearch} defaultOrder={defaultOrder} onSave={save} />; if (meta.key === 'projects') return <ProjectForm initial={row as AdminProject} defaultOrder={defaultOrder} onSave={save} />; return <QualificationForm initial={row as AdminQualification} defaultOrder={defaultOrder} onSave={save} />; }; return <main className="mx-auto max-w-[1460px] px-5 py-8 sm:px-8"><button type="button" onClick={() => navigate(`/admin/${meta.key}`)} className="text-sm font-semibold text-slate-500">← 戻る</button><h1 className="mt-5 text-4xl font-extrabold tracking-tight">{meta.label}{id === 'new' ? 'を追加' : '編集'}</h1><section className="mt-6 border border-slate-200 bg-white p-6 shadow-sm">{error && <p className="mb-5 text-sm text-rose-500">{error}</p>}{!loading && (id === 'new' || row) ? form() : <p className="py-12 text-center text-sm text-slate-500">読み込み中...</p>}</section></main>; };

const ProfilePage = () => { const [profile, setProfile] = useState<AdminProfile>(); const [error, setError] = useState(''); useEffect(() => { getProfileForAdmin().then(setProfile).catch((reason) => setError(reason.message)); }, []); return <main className="mx-auto max-w-[1460px] px-5 py-8 sm:px-8"><button type="button" onClick={() => navigate('/admin')} className="text-sm font-semibold text-slate-500">← ダッシュボードに戻る</button><h1 className="mt-5 text-4xl font-extrabold">Profile編集</h1><section className="mt-6 border border-slate-200 bg-white p-6 shadow-sm">{error && <p className="mb-5 text-sm text-rose-500">{error}</p>}{profile ? <ProfileForm initial={profile} onSave={async (value) => { try { await saveProfile(value); navigate('/admin'); } catch (reason) { setError(reason instanceof Error ? reason.message : '保存できませんでした。'); } }} /> : !error && <p className="py-12 text-center text-sm text-slate-500">読み込み中...</p>}</section></main>; };

const AdminCMS = () => { const [path, setPath] = useState(window.location.pathname); const [session, setSession] = useState<Session | null>(); const [admin, setAdmin] = useState<boolean>(); const [counts, setCounts] = useState<Partial<Record<AdminContentKey, number>>>({}); useEffect(() => { const update = async () => { const next = await getAdminSession(); setSession(next); setAdmin(next ? await isCurrentUserAdmin() : false); }; update(); const subscription = onAdminAuthChange(update); const pop = () => setPath(window.location.pathname); window.addEventListener('popstate', pop); return () => { subscription.unsubscribe(); window.removeEventListener('popstate', pop); }; }, []); useEffect(() => { if (admin) Promise.all(metas.map(async (meta) => [meta.key, (await getRecords(meta.key)).length] as const)).then((entries) => setCounts(Object.fromEntries(entries))).catch(() => undefined); }, [admin]); if (session === undefined || admin === undefined) return <main className="grid min-h-screen place-items-center text-sm text-slate-500">認証状態を確認しています...</main>; if (!session) return <Login />; if (!admin) return <Login error="このGoogleアカウントには管理画面へのアクセス権限がありません。" />; const parts = path.split('/').filter(Boolean); const meta = metas.find((entry) => entry.key === parts[1]); let body: React.ReactNode = <Dashboard counts={counts} />; if (path === '/admin/profile') body = <ProfilePage />; else if (path === '/admin/admins') body = <AdminsPage currentEmail={session.user.email ?? ''} onBack={() => navigate('/admin')} />; else if (meta) body = parts[2] ? <EditPage meta={meta} id={parts[2]} /> : <ListPage meta={meta} />; return <div className="min-h-screen bg-[#fafbfe] text-slate-900"><Header session={session} />{body}</div>; };
export default AdminCMS;
