import React, { useState } from 'react';
import { uploadAdminImage } from '../../services/adminService';
import { AdminEducationWork } from '../../types/admin';
import { Field, ImageField, inputClass, StatusFields, TagEditor } from './FormControls';

export const EducationWorkForm = ({ initial, defaultOrder = 0, onSave }: { initial?: AdminEducationWork; defaultOrder?: number; onSave: (value: Omit<AdminEducationWork, 'id' | 'updated_at'>) => Promise<void> }) => {
  const [value, setValue] = useState<Omit<AdminEducationWork, 'id' | 'updated_at'>>({ type: initial?.type ?? 'Education', short_work: initial?.short_work ?? false, date_label: initial?.date_label ?? '', title: initial?.title ?? '', subtitle: initial?.subtitle ?? '', logo_path: initial?.logo_path ?? '', material_url: initial?.material_url ?? '', tags: initial?.tags ?? [], is_current: initial?.is_current ?? false, display_order: initial?.display_order ?? defaultOrder, is_published: initial?.is_published ?? true });
  const [preview, setPreview] = useState<string>(); const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  const update = <K extends keyof typeof value>(key: K, next: (typeof value)[K]) => setValue({ ...value, [key]: next });
  const category = value.type === 'Education' ? 'Education' : value.short_work ? 'ShortWork' : 'MiddleLongWork';
  const updateCategory = (next: 'Education' | 'ShortWork' | 'MiddleLongWork') => setValue({ ...value, type: next === 'Education' ? 'Education' : 'Work', short_work: next === 'ShortWork' });
  const selectImage = async (file: File) => { setUploading(true); try { update('logo_path', await uploadAdminImage(file, 'education-work')); setPreview(URL.createObjectURL(file)); } catch { setError('画像をアップロードできませんでした。'); } finally { setUploading(false); } };
  return <form onSubmit={(event) => { event.preventDefault(); if (!value.title || !value.subtitle || !value.date_label || !value.logo_path) return setError('必須項目を入力してください。'); onSave(value); }} className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5"><Field label="Type" required><select value={category} onChange={(event) => updateCategory(event.target.value as 'Education' | 'ShortWork' | 'MiddleLongWork')} className={inputClass}><option value="Education">Education</option><option value="ShortWork">ShortWork</option><option value="MiddleLongWork">Middle・LongWork</option></select></Field><Field label="Date" required><input value={value.date_label} onChange={(event) => update('date_label', event.target.value)} className={inputClass} /></Field><Field label="Title" required><input value={value.title} onChange={(event) => update('title', event.target.value)} className={inputClass} /></Field><Field label="Subtitle" required><input value={value.subtitle} onChange={(event) => update('subtitle', event.target.value)} className={inputClass} /></Field><Field label="Material URL"><input value={value.material_url} onChange={(event) => update('material_url', event.target.value)} type="url" className={inputClass} /></Field><TagEditor label="Tags" values={value.tags} onChange={(next) => update('tags', next)} /><StatusFields published={value.is_published} onPublished={(next) => update('is_published', next)} current={value.is_current} onCurrent={(next) => update('is_current', next)} showCurrent order={value.display_order} onOrder={(next) => update('display_order', next)} />{error && <p className="text-sm text-rose-500">{error}</p>}<button disabled={uploading} className="h-11 border border-indigo-600 bg-indigo-600 px-7 text-sm font-semibold text-white disabled:opacity-50">{uploading ? 'アップロード中...' : '保存'}</button></div><ImageField label="ロゴプレビュー" path={value.logo_path} preview={preview} onSelect={selectImage} /></form>;
};
