import React, { useState } from 'react';
import { AdminNews } from '../../types/admin';
import { Field, inputClass, StatusFields, textareaClass } from './FormControls';

export const NewsForm = ({ initial, onSave }: { initial?: AdminNews; onSave: (value: Omit<AdminNews, 'id' | 'updated_at'>) => Promise<void> }) => {
  const [value, setValue] = useState<Omit<AdminNews, 'id' | 'updated_at'>>({ category: initial?.category ?? 'Research', date_label: initial?.date_label ?? '', title: initial?.title ?? '', description: initial?.description ?? '', link_url: initial?.link_url ?? '', display_order: initial?.display_order ?? 0, is_published: initial?.is_published ?? true });
  const [error, setError] = useState('');
  const update = <K extends keyof typeof value>(key: K, next: (typeof value)[K]) => setValue({ ...value, [key]: next });
  return <form onSubmit={(event) => { event.preventDefault(); if (!value.title || !value.description) return setError('タイトルと説明を入力してください。'); onSave(value); }} className="space-y-5"><Field label="Category" required><select value={value.category} onChange={(event) => update('category', event.target.value as AdminNews['category'])} className={inputClass}><option>Internship</option><option>Job Hunting</option><option>Research</option></select></Field><Field label="Date"><input value={value.date_label} onChange={(event) => update('date_label', event.target.value)} placeholder="2026 / 8" className={inputClass} /></Field><Field label="Title" required><input value={value.title} onChange={(event) => update('title', event.target.value)} className={inputClass} /></Field><Field label="Description" required><textarea value={value.description} onChange={(event) => update('description', event.target.value)} rows={5} className={textareaClass} /></Field><Field label="Link"><input value={value.link_url} onChange={(event) => update('link_url', event.target.value)} type="url" className={inputClass} /></Field><StatusFields published={value.is_published} onPublished={(next) => update('is_published', next)} order={value.display_order} onOrder={(next) => update('display_order', next)} />{error && <p className="text-sm text-rose-500">{error}</p>}<button className="h-11 border border-indigo-600 bg-indigo-600 px-7 text-sm font-semibold text-white hover:bg-indigo-500">保存</button></form>;
};
