import React, { useState } from 'react';
import { uploadAdminImage } from '../../services/adminService';
import { AdminProfile } from '../../types/admin';
import { Field, ImageField, inputClass } from './FormControls';

export const ProfileForm = ({ initial, onSave }: { initial: AdminProfile; onSave: (value: AdminProfile) => Promise<void> }) => {
  const [value, setValue] = useState(initial); const [profilePreview, setProfilePreview] = useState<string>(); const [heroPreview, setHeroPreview] = useState<string>(); const [error, setError] = useState('');
  const update = <K extends keyof AdminProfile>(key: K, next: AdminProfile[K]) => setValue({ ...value, [key]: next });
  const upload = async (file: File, key: 'profile_image_path' | 'hero_image_path') => { try { const path = await uploadAdminImage(file, key === 'profile_image_path' ? 'profile' : 'hero'); update(key, path); key === 'profile_image_path' ? setProfilePreview(URL.createObjectURL(file)) : setHeroPreview(URL.createObjectURL(file)); } catch { setError('画像をアップロードできませんでした。'); } };
  return <form onSubmit={(event) => { event.preventDefault(); if (!value.name || !value.english_name || !value.role || !value.email) return setError('必須項目を入力してください。'); onSave(value); }} className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="grid gap-5 md:grid-cols-2"><Field label="Name" required><input value={value.name} onChange={(event) => update('name', event.target.value)} className={inputClass} /></Field><Field label="English Name" required><input value={value.english_name} onChange={(event) => update('english_name', event.target.value)} className={inputClass} /></Field><Field label="Role" required><input value={value.role} onChange={(event) => update('role', event.target.value)} className={inputClass} /></Field><Field label="Email" required><input value={value.email} onChange={(event) => update('email', event.target.value)} type="email" className={inputClass} /></Field><Field label="University Name"><input value={value.university_name} onChange={(event) => update('university_name', event.target.value)} className={inputClass} /></Field><Field label="Department Name"><input value={value.department_name} onChange={(event) => update('department_name', event.target.value)} className={inputClass} /></Field><Field label="Department URL"><input value={value.department_url} onChange={(event) => update('department_url', event.target.value)} type="url" className={inputClass} /></Field><Field label="Lab Name"><input value={value.lab_name} onChange={(event) => update('lab_name', event.target.value)} className={inputClass} /></Field><Field label="Lab URL"><input value={value.lab_url} onChange={(event) => update('lab_url', event.target.value)} type="url" className={inputClass} /></Field><Field label="GitHub"><input value={value.social_links.github ?? ''} onChange={(event) => update('social_links', { ...value.social_links, github: event.target.value })} type="url" className={inputClass} /></Field><Field label="Twitter"><input value={value.social_links.twitter ?? ''} onChange={(event) => update('social_links', { ...value.social_links, twitter: event.target.value })} type="url" className={inputClass} /></Field>{error && <p className="text-sm text-rose-500 md:col-span-2">{error}</p>}<button className="h-11 w-fit border border-indigo-600 bg-indigo-600 px-7 text-sm font-semibold text-white">保存</button></div><aside className="space-y-5"><ImageField label="Profile Image" path={value.profile_image_path} preview={profilePreview} onSelect={(file) => upload(file, 'profile_image_path')} /><ImageField label="Hero Image" path={value.hero_image_path} preview={heroPreview} onSelect={(file) => upload(file, 'hero_image_path')} /></aside></form>;
};
