import React, { useState } from 'react';
import { uploadAdminImage } from '../../services/adminService';
import { AdminResearch } from '../../types/admin';
import { Field, ImageField, inputClass, StatusFields, TagEditor, textareaClass } from './FormControls';

export const ResearchForm = ({ initial, defaultOrder = 0, onSave }: { initial?: AdminResearch; defaultOrder?: number; onSave: (value: Omit<AdminResearch, 'id' | 'updated_at'>) => Promise<void> }) => {
  const [value, setValue] = useState<Omit<AdminResearch, 'id' | 'updated_at'>>({ title: initial?.title ?? '', description: initial?.description ?? '', image_path: initial?.image_path ?? '', tags: initial?.tags ?? [], link_url: initial?.link_url ?? '', is_current: initial?.is_current ?? false, display_order: initial?.display_order ?? defaultOrder, is_published: initial?.is_published ?? true });
  const [preview, setPreview] = useState<string>(); const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  const update = <K extends keyof typeof value>(key: K, next: (typeof value)[K]) => setValue({ ...value, [key]: next });
  const selectImage = async (file: File) => { setUploading(true); try { update('image_path', await uploadAdminImage(file, 'research')); setPreview(URL.createObjectURL(file)); } catch { setError('画像をアップロードできませんでした。'); } finally { setUploading(false); } };
  return <form onSubmit={(event) => { event.preventDefault(); if (!value.title || !value.description || !value.image_path) return setError('必須項目を入力してください。'); onSave(value); }} className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5"><Field label="Title" required><input value={value.title} onChange={(event) => update('title', event.target.value)} className={inputClass} /></Field><Field label="Description" required><textarea value={value.description} onChange={(event) => update('description', event.target.value)} rows={6} className={textareaClass} /></Field><TagEditor label="Tags" values={value.tags} onChange={(next) => update('tags', next)} /><Field label="Link"><input value={value.link_url} onChange={(event) => update('link_url', event.target.value)} type="url" className={inputClass} /></Field><StatusFields published={value.is_published} onPublished={(next) => update('is_published', next)} current={value.is_current} onCurrent={(next) => update('is_current', next)} showCurrent order={value.display_order} onOrder={(next) => update('display_order', next)} />{error && <p className="text-sm text-rose-500">{error}</p>}<button disabled={uploading} className="h-11 border border-indigo-600 bg-indigo-600 px-7 text-sm font-semibold text-white disabled:opacity-50">{uploading ? 'アップロード中...' : '保存'}</button></div><ImageField label="研究画像プレビュー" path={value.image_path} preview={preview} onSelect={selectImage} /></form>;
};
